# Generated by Django 5.2.17 on 2026-09-18 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('year', models.PositiveIntegerField(verbose_name='ano')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(verbose_name='fim')),
                ('status', models.CharField(choices=[('active', 'Em andamento'), ('closed', 'Encerrado'), ('planned', 'Planejado')], default='active', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'ciclo',
                'verbose_name_plural': 'ciclos',
                'ordering': ['-year', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('mid', 'Intercalar'), ('final', 'Final')], max_length=10, verbose_name='tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('draft', 'Em preenchimento'), ('submitted', 'Enviada'), ('validated', 'Validada')], default='pending', max_length=15, verbose_name='status')),
                ('self_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='nota de autoavaliação')),
                ('manager_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='nota da chefia')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.cycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-updated_at'],
            },
        ),
    ]
