# Generated by Django 5.2.17 on 2026-09-18 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('evidence', 'Evidência'), ('feedback', 'Feedback'), ('adjustment', 'Ajuste de rota')], max_length=15, verbose_name='tipo')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('content', models.TextField(verbose_name='registro')),
                ('next_step', models.CharField(blank=True, max_length=220, verbose_name='próximo passo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups_authored', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.cycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acompanhamento',
                'verbose_name_plural': 'acompanhamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('organizational', 'Organizacional'), ('departmental', 'Departamental'), ('individual', 'Individual')], max_length=20, verbose_name='nível')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('measure', models.CharField(blank=True, max_length=220, verbose_name='indicador de sucesso')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Em andamento'), ('completed', 'Concluído')], default='draft', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='core.cycle')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'objetivo',
                'verbose_name_plural': 'objetivos',
                'ordering': ['category', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Chefia imediata'), ('hr', 'Recursos Humanos'), ('council', 'Conselho de Administração')], max_length=15, verbose_name='papel')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('returned', 'Devolvida')], default='pending', max_length=15, verbose_name='status')),
                ('comment', models.TextField(blank=True, verbose_name='comentário')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.cycle')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.evaluation')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'validação',
                'verbose_name_plural': 'validações',
                'ordering': ['status', 'role'],
            },
        ),
    ]
