# Generated by Django 5.2.17 on 2026-09-22 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_followup_objective_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Em andamento'), ('completed', 'Concluído')], default='draft', max_length=15, verbose_name='status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'objetivo departamental',
                'verbose_name_plural': 'objetivos departamentais',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='IndividualObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Em andamento'), ('completed', 'Concluído')], default='draft', max_length=15, verbose_name='status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('department_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_objectives', to='core.departmentobjective')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_objectives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'objetivo individual',
                'verbose_name_plural': 'objetivos individuais',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Em andamento'), ('completed', 'Concluído')], default='draft', max_length=15, verbose_name='status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_objectives', to='core.cycle')),
            ],
            options={
                'verbose_name': 'objetivo institucional',
                'verbose_name_plural': 'objetivos institucionais',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='departmentobjective',
            name='institutional_objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_objectives', to='core.institutionalobjective'),
        ),
    ]
