# Generated by Django 5.2.17 on 2026-09-23 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_departmentobjective_individualobjective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_managed', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='departmentobjective',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='core.department', verbose_name='departamento'),
        ),
    ]
