# Generated by Django 5.2.17 on 2026-09-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_department_manager_userdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descrição')),
                ('type', models.IntegerField(verbose_name='tipo')),
                ('domain_description', models.CharField(max_length=100, verbose_name='descrição do domínio')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'domínio',
                'verbose_name_plural': 'domínios',
                'db_table': 'domain',
                'ordering': ['description'],
            },
        ),
    ]
