# Generated by Django 5.2.17 on 2026-09-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentobjective',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_objectives', to='core.domain', verbose_name='domínio'),
        ),
        migrations.AddField(
            model_name='individualobjective',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_objectives', to='core.domain', verbose_name='domínio'),
        ),
    ]
