# Generated by Django 5.2.17 on 2026-09-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_departmentobjective_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalobjective',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutional_objectives', to='core.domain', verbose_name='domínio'),
        ),
    ]
