# Generated by Django 5.2.17 on 2026-09-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_institutionalobjective_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles', to='core.domain', verbose_name='domínio'),
        ),
    ]
