# Generated by Django 5.2.17 on 2026-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_move_department_approval_to_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualobjective',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de fim'),
        ),
        migrations.AddField(
            model_name='individualobjective',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de início'),
        ),
    ]
