# Generated by Django 5.2.17 on 2026-10-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ensure_collaborator_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('individual_objective', models.ForeignKey(db_column='objetivo_individual_id', on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_records', to='core.individualobjective', verbose_name='objetivo individual')),
            ],
            options={
                'verbose_name': 'registo de ocorrência',
                'verbose_name_plural': 'registos de ocorrências',
                'db_table': 'registo_ocorrencia',
                'ordering': ['-date_created'],
            },
        ),
    ]
