# Generated by Django 5.2.17 on 2026-10-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_registoocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprovacaotarefa',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='departmentobjective',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='followup',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='individualobjective',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='institutionalobjective',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='objective',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='registoocorrencia',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='validation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='ativo'),
        ),
    ]
