# Generated by Django 5.2.17 on 2026-10-08 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aprovacaotarefa_is_active_cycle_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualobjective',
            name='percentagem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percentagem'),
        ),
    ]
